#!/usr/bin/env bash
# Install/update the per-user bored service. Run as the account that owns the
# tracker state and the repository whose worktrees bored will create.
set -euo pipefail

usage() {
  cat <<'EOF'
Usage:
  scripts/install-systemd-user-service.sh --worker 'WORKER COMMAND' [options]

Options:
  --source DIR       bored checkout to run (default: this script's checkout)
  --root DIR         durable bored state directory (default: ~/.local/state/bored)
  --repo DIR         git repository in which worker worktrees are made
                     (default: --source; set this to the Beckett checkout in production)
  --port PORT        localhost HTTP port (default: 7770)
  --owner-dm TARGET  owner announcement target (default: owner)
  --max-workers N    global worker cap (default: 4)
  --start            restart the service after enabling it
  -h, --help         show this help

The script always builds the selected checkout, installs/updates the unit,
enables it for future user-manager starts, and enables user lingering so it
also starts after boot without an interactive login. It never starts the
service unless --start is supplied.
EOF
}

script_dir=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)
source_dir=$(cd -- "$script_dir/.." && pwd -P)
root_dir="${XDG_STATE_HOME:-$HOME/.local/state}/bored"
repo_dir=""
port=7770
owner_dm="owner"
max_workers=4
worker=""
start=0

while (($#)); do
  case "$1" in
    --source) source_dir=$2; shift 2 ;;
    --root) root_dir=$2; shift 2 ;;
    --repo) repo_dir=$2; shift 2 ;;
    --port) port=$2; shift 2 ;;
    --owner-dm) owner_dm=$2; shift 2 ;;
    --max-workers) max_workers=$2; shift 2 ;;
    --worker) worker=$2; shift 2 ;;
    --start) start=1; shift ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown option: $1" >&2; usage >&2; exit 2 ;;
  esac
done

if [[ -z "$worker" ]]; then
  echo "--worker is required (it is the command bored spawns for each seat)." >&2
  usage >&2
  exit 2
fi
if [[ ! "$port" =~ ^[0-9]+$ ]] || ((port < 1 || port > 65535)); then
  echo "--port must be an integer from 1 through 65535." >&2
  exit 2
fi
if [[ ! "$max_workers" =~ ^[1-9][0-9]*$ ]]; then
  echo "--max-workers must be a positive integer." >&2
  exit 2
fi

source_dir=$(cd -- "$source_dir" && pwd -P)
repo_dir=${repo_dir:-$source_dir}
repo_dir=$(cd -- "$repo_dir" && pwd -P)
if [[ ! -f "$source_dir/package.json" || ! -f "$source_dir/deploy/systemd/bored.service" ]]; then
  echo "--source must be a bored checkout containing package.json and deploy/systemd/bored.service." >&2
  exit 2
fi
if ! git -C "$repo_dir" rev-parse --is-inside-work-tree >/dev/null 2>&1; then
  echo "--repo must be a git worktree: $repo_dir" >&2
  exit 2
fi
node_bin=$(command -v node || true)
if [[ -z "$node_bin" ]]; then
  echo "node is required but was not found in PATH." >&2
  exit 2
fi

# EnvironmentFile uses single quotes for literal values. The explicit refusal
# avoids generating a unit that parses a surprising worker command.
for value in "$node_bin" "$source_dir/dist/cli.js" "$root_dir" "$repo_dir" "$worker" "$owner_dm"; do
  if [[ "$value" == *$'\n'* || "$value" == *"'"* ]]; then
    echo "service settings cannot contain a newline or single quote." >&2
    exit 2
  fi
done

(
  cd -- "$source_dir"
  npm ci
  npm run build
)

config_home="$HOME/.config"
config_dir="$config_home/bored"
unit_dir="$config_home/systemd/user"
mkdir -p -- "$config_dir" "$unit_dir" "$root_dir"

# Write atomically so a service restart cannot observe a partial configuration.
env_tmp=$(mktemp "$config_dir/bored.env.XXXXXX")
trap 'rm -f "$env_tmp"' EXIT
cat >"$env_tmp" <<EOF
# Generated by install-systemd-user-service.sh. Re-run the script to update.
BORED_NODE='$node_bin'
BORED_CLI='$source_dir/dist/cli.js'
BORED_ROOT='$root_dir'
BORED_REPO='$repo_dir'
BORED_WORKER='$worker'
BORED_PORT='$port'
BORED_MAX_WORKERS='$max_workers'
BORED_OWNER_DM='$owner_dm'
EOF
chmod 600 "$env_tmp"
mv -f -- "$env_tmp" "$config_dir/bored.env"
trap - EXIT
install -m 0644 "$source_dir/deploy/systemd/bored.service" "$unit_dir/bored.service"

systemctl --user daemon-reload
systemctl --user enable bored.service
# A user unit only starts at boot when the user manager survives logout.
loginctl enable-linger "$USER"

if ((start)); then
  systemctl --user restart bored.service
fi

echo "Installed and enabled bored.service."
echo "Health URL: http://127.0.0.1:$port/health"
if (( ! start )); then
  echo "Not started (pass --start after reviewing $config_dir/bored.env)."
fi
